# Generated by Django 5.0.1 on 2024-04-16 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('question_1', models.CharField(blank=True, max_length=50, null=True)),
                ('question_2', models.CharField(blank=True, max_length=50, null=True)),
                ('question_3', models.CharField(blank=True, max_length=50, null=True)),
                ('question_4', models.CharField(blank=True, max_length=50, null=True)),
                ('question_5', models.CharField(blank=True, max_length=50, null=True)),
                ('question_6', models.CharField(blank=True, max_length=50, null=True)),
                ('question_7', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.DateField()),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gen7_total_attendees', models.IntegerField(blank=True, default=0, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participant')),
            ],
        ),
    ]
