# Generated by Django 5.0.1 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.AddField(
            model_name='participant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
