# Generated by Django 5.0.1 on 2024-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_participant_additional_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
