# Generated by Django 5.0.1 on 2024-11-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_child_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='question_1',
            new_name='accommodation',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_2',
            new_name='attending_gtc',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_3',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_5',
            new_name='impartation',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_4',
            new_name='registered_student',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_6',
            new_name='total_attending_gtc',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_7',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='question_8',
            new_name='volunteering',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='additional_message',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gen7_total_attendees',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='spouse_name',
        ),
    ]
