# Generated by Django 5.0.1 on 2024-11-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_question_1_participant_accommodation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='city',
            new_name='region',
        ),
    ]
