# Generated by Django 5.0.1 on 2024-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_participant_personal_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='total_attending_gtc',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
