# Generated by Django 5.0.1 on 2024-12-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_participant_total_attending_gtc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='total_attending_gtc',
        ),
        migrations.AddField(
            model_name='participant',
            name='spouse_or_child',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
