# Generated by Django 5.0.1 on 2024-12-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_remove_participant_total_attending_gtc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
