# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_participant_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='volunteering',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='coming_with_children',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
