# Generated by Django 5.0.1 on 2024-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='twi_video_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_link',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='twi_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(default=42443, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_source',
            field=models.CharField(choices=[('youtube', 'Y'), ('vimeo', 'V')], max_length=50),
        ),
    ]
