# Generated by Django 5.0.1 on 2024-02-10 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0003_alter_course_slug_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
