# Generated by Django 5.0.1 on 2024-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0004_course_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(upload_to='lesson_thumbnails'),
        ),
    ]
