# Generated by Django 5.0.1 on 2024-10-02 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0006_comment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2090)]),
        ),
    ]
